dist: trusty

sudo: false

language: node_js

node_js:
 - 8.6.0 
 
branches:
  only:
    - master
    
cache:
  bundler: true
  directories:
    - node_modules # NPM packages

install:
  - npm set progress=false
  - npm i
  - cd functions && npm i ; cd -

script:
  - npm run build

after_success:
  - npm run firebase -- deploy --token $FIREBASE_TOKEN